name: Main

on: [push]

jobs: 
    build_and_lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
            cache: 'pip' 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Analysing the code with pylint
          run: |
              pylint $(git ls-files '*.py')

    lint: 
        runs-on: ubuntu-latest
        steps:
        - name: Analysing the code with pylint
          run: |
              pylint $(git ls-files '*.py')
            
    health-check:
        needs: build_and_lint
        runs-on: ubuntu-latest
        steps:
            - name: Ping my site
              uses: Leocardoso94/is-my-site-up@v1.2
              with:
                site: https://sa64r-education-youtuber-gpt.streamlit.app/
